FROM ubuntu@sha256:9cbed754112939e914291337b5e554b07ad7c392491dba6daf25eef1332a22e8
ENV DEBIAN_FRONTEND=noninteractive TZ=UTC
RUN apt-get update \
 && apt-get install -y --no-install-recommends g++ libboost-all-dev libssl-dev ca-certificates \
 && rm -rf /var/lib/apt/lists/*