FROM ubuntu@sha256:4e0171b9275e12d375863f2b3ae9ce00a4c53ddda176bd55868df97ac6f21a6e
ENV DEBIAN_FRONTEND=noninteractive TZ=UTC
RUN apt-get update \
 && apt-get install -y --no-install-recommends g++ libboost-all-dev libssl-dev ca-certificates \
 && rm -rf /var/lib/apt/lists/*