name: Build and Release tty-ws-agent

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}/tty-ws-agent-builder

jobs:
  # ------------------------------------------------------------
  # Step 1: Build & push builder images
  # ------------------------------------------------------------
  build-builder-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22.04, 24.04]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image names
        id: vars
        run: |
          echo "IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}:${{ matrix.version }}" >> $GITHUB_OUTPUT
          echo "CACHE=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}:${{ matrix.version }}-cache" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/Dockerfile.ubuntu${{ matrix.version }}
          push: true
          tags: ${{ steps.vars.outputs.IMAGE }}
          cache-from: type=registry,ref=${{ steps.vars.outputs.CACHE }}
          cache-to: type=registry,ref=${{ steps.vars.outputs.CACHE }},mode=max

  # ------------------------------------------------------------
  # Step 2: Compile binaries
  # ------------------------------------------------------------
  build-multi-docker:
    needs: build-builder-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22.04, 24.04]

    steps:
      - uses: actions/checkout@v4

      - name: Build binary for Ubuntu ${{ matrix.version }}
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}:${{ matrix.version }}
          docker pull $IMAGE
          docker run --rm -v $(pwd):/src -w /src $IMAGE \
            bash -c "g++ -std=c++17 -O2 -DNDEBUG tty-ws-agent.cpp -o tty-ws-agent-ubuntu${{ matrix.version }} -lboost_system -lssl -lcrypto -lpthread && strip tty-ws-agent-ubuntu${{ matrix.version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: tty-ws-agent-binaries-${{ matrix.version }}
          path: tty-ws-agent-ubuntu${{ matrix.version }}
          retention-days: 5

  # ------------------------------------------------------------
  # Step 3: Release assets (matrix for all versions)
  # ------------------------------------------------------------
  release:
    needs: build-multi-docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22.04, 24.04]

    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: tty-ws-agent-binaries-${{ matrix.version }}
          path: ./release-bin

      - name: Upload ${{ matrix.version }} asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-bin/tty-ws-agent-ubuntu${{ matrix.version }}
          asset_name: tty-ws-agent-ubuntu${{ matrix.version }}
          asset_content_type: application/octet-stream